### ISSUE TITLE
gcc -m64 option breaks X86 32 bit build

### ISSUE THREAD

**Issue by LeeTibbert** [olofwalker/scala-native-example#2]
makefile uses a gcc -m64 option.
```
gcc -m64 -shared -c src/main/c/stub.c -o target/libstub.so
```
Is this option strictly necessary on 64 bit machines? 
I believe that gcc will do the right thing on each architecture
and that the option is redundant/unnecessary.

The reason that I ask is that the -m64 breaks a the "clone & go"
experience on X86 32-bit.   I changed my local copy of
makefile to remove the option & any weird behaviour
seems to be due to me, not the deleted option.

Thank you,
Lee

PS:
I also changed the makefile to make it easier to use the
"make" idiom of using $(CC). This makes it easier to use
clang, the same compiler used by scala-native. 

Clang's superior error reporting helped me twig to the ".o for .so" idiom.
```
CC = clang

all : 
	$(CC) -shared  src/main/c/stub.c -o target/libstub.so
```

**Comment by olofwalker** [comment]
Scala Native is currently 64 bit only

**Comment by LeeTibbert** [comment]
Funny, scala-native on my 32 bit machine works just fine
(as long as one stays away from fwrite & those who call it
(scala printf, etc.). ;-)   The light bulb on my machine also
works just fine.

It took only a few local edits, now documented as issues in scala-native git,

There are probably a few gotcha's laying in wait for me, but so far getting
linking and running with shared libraries (.so) has been the hardest part.

I agree entirely that the avant garde needs to travel light & fast, unencumbered
by legacy. However, simple changes to not exclude the trailing edge can add weight of numbers.

If, as I believe, the -m64 is redundant/unnecessary on 64 bit machines, why
not just simplify the cognitive load for all and drop it? 

Your house, your preferences. Thank you for at least
considering the change. 

If approved, I can do a PR to drop or conditionally compile the option
(but have no way to test on 64 bit).

Cheers,

Lee

**Comment by LeeTibbert** [comment]
Another option is to add a line to README.md stating that this project is 64 bit only.
That warns 32 bit people that "clone & go" may not work out-of-the-box & that they
should check the git Issues first.

**Comment by olofwalker** [comment]
Added wording about this in the readme file.
