### ISSUE TITLE
Sbt warning for <<= in build.sbt

### ISSUE THREAD

**Issue by LeeTibbert** [olofwalker/scala-native-example#3]
sbt 0.13.13 gives a deprecation warning about the following line in this project's build.sbt
```
compile in Compile <<= (compile in Compile).dependsOn(make)
```
This warning makes the "clone & go" experience more time consuming & less pleasant.

When I follow the [directions](http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html) in the warning, sbt is happy, making me happy.
```                                                           
compile in Compile := (compile in Compile dependsOn make).value
```
sbt 1.0.0, when it happens, is likely to make this a hard error, rather than a warning.

@olofwalker If you would like & approve, I could submit a pull request for this change.
I do not want to be just complaining and not offering to do some work to partially
repay the benefit I have gotten from this project. Please advise.

**Comment by olofwalker** [comment]
@LeeTibbert Please do submit a PR and I will look and approve

**Comment by LeeTibbert** [comment]
Done,
 
Let me know if I need to do an electronic signature to a contributor agreement or such.

Thank you for looking at and considering this change.

**Comment by olofwalker** [comment]
Merged
